// postsSlice.js
import { createSlice } from '@reduxjs/toolkit';

// Create a slice for posts
const postsSlice = createSlice({
  name: 'posts',
  initialState: [], // Initial state is an empty array
  reducers: {
    setPosts: (state, action) => {
      return action.payload; // Set the posts array with the payload data
    },
  },
});

// Export the actions generated by createSlice
export const { setPosts } = postsSlice.actions;

// Export the reducer to be used in the store
export default postsSlice.reducer;
